import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import PromotionalText from "@/components/PromotionalText";
import Navbar from "@/components/Navbar/Navbar";
import { constantNumbers } from "@/utils/constants";

const rubik = Rubik({
  variable: "--font-rubik-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} antialiased bg-background text-foreground`}
      >
        <div className="space-y-2 bg-primary">
          <PromotionalText />
          <p className="text-center text-white">
            free shiping on all orders over $ {constantNumbers("FREE_SHIPPING")}
          </p>
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
