import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "../styles/globals.css";

const rubik = Rubik({
  variable: "--font-rubik-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
